name: Notify on Issue Creation

on:
  issues:
    types: [opened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚀 New Issue Created: #${{ github.event.issue.number }} - ${{ github.event.issue.title }}"
          html_body: |
            <h1>🚀 New Issue Created</h1>
            <p>A new issue has been created in your repository.</p>

            <h2>Issue Details</h2>
            <ul>
              <li><strong>Issue Title:</strong> ${{ github.event.issue.title }}</li>
              <li><strong>Issue Number:</strong> #${{ github.event.issue.number }}</li>
              <li><strong>Created by:</strong> ${{ github.event.issue.user.login }}</li>
            </ul>

            <p>You can view the issue <a href="${{ github.event.issue.html_url }}">here</a>.</p>

          to: "daryakerman2002@gmail.com"
          from: ${{ secrets.EMAIL_USER }}
