name: Send Email to Owner on Push

on: push

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚀 Code Pushed to Your Repository"
          # Using HTML format for the body
          html_body: |
            <h1>🚀 Code Push Notification</h1>
            <p>A new commit has been pushed to your repository.</p>

            <h2>Commit Details</h2>
            <ul>
              <li><strong>Commit Hash:</strong> ${{ github.sha }}</li>
              <li><strong>Committer:</strong> ${{ github.actor }}</li>
              <li><strong>Branch:</strong> ${{ github.ref }}</li>
            </ul>

            <p>You can view the commit <a href="https://github.com/${{ github.repository }}/commit/${{ github.sha }}">here</a>.</p>

          to: "daryakerman2002@gmail.com"
          from: ${{ secrets.EMAIL_USER }}
